name: voco_riverpod_mvc
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Core
  equatable: ^2.0.5
  get_it: ^7.6.7

  # Config
  envied: ^0.5.3
  json_annotation: ^4.8.1
  easy_localization: ^3.0.3

  # Utility
  logger: ^2.0.2+1
  kartal: ^3.5.0
  email_validator: ^2.1.17

  # Storage
  flutter_secure_storage: ^9.0.0

  # State Managment
  riverpod: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  auto_route_generator: ^7.3.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
